"""дополняет таблицы заданий

Revision ID: 920ca0aa0ea3
Revises: e3d254cf74f4
Create Date: 2023-12-11 20:40:52.871135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920ca0aa0ea3'
down_revision: Union[str, None] = 'e3d254cf74f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'question_types', ['SingleChoice', 'MultipleChoice', 'Open'],
                        [('questions', 'type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'task_types', ['Test', 'Discussion'],
                        [('task_units', 'type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'task_types', ['Test'],
                        [('task_units', 'type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'question_types', ['SingleChoice', 'MultipleChoice'],
                        [('questions', 'type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
