"""Добавляет таблицы вопросов и ответов

Revision ID: 5bc05f78249a
Revises: 5aa9681ef1db
Create Date: 2023-11-15 12:05:18.429020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc05f78249a'
down_revision: Union[str, None] = '5aa9681ef1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum(name='question_types'), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('correct_answer_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_employees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum(name='task_states'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'employee_id')
    )
    op.add_column('tasks', sa.Column('type', sa.Enum(name='task_types'), nullable=False))
    op.add_column('tasks', sa.Column('requires_review', sa.Boolean(), nullable=False))
    op.drop_column('tasks', 'content')
    op.drop_column('tasks', 'is_accomplished')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_accomplished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'requires_review')
    op.drop_column('tasks', 'type')
    op.drop_table('task_employees')
    op.drop_table('questions')
    op.drop_table('answers')
    # ### end Alembic commands ###
