"""меняет в модели уровня name на title

Revision ID: da06417476fd
Revises: 29ed19cdffbf
Create Date: 2023-11-19 00:24:59.794292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da06417476fd'
down_revision: Union[str, None] = '29ed19cdffbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('levels', 'module_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('levels', 'name')
    op.alter_column('modules', 'map_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'map_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('levels', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('levels', 'module_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('levels', 'title')
    # ### end Alembic commands ###
