"""модуль и уровни обязательно привязаны к родителю

Revision ID: 4e3cf7a2acb2
Revises: e8496d8a36fc
Create Date: 2023-11-19 21:46:34.041826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3cf7a2acb2'
down_revision: Union[str, None] = 'e8496d8a36fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'module_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('modules', 'map_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'map_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('levels', 'module_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
