"""добавляет каскадное удаление моделей уровней

Revision ID: c4fba311583c
Revises: 5b1fc71a077e
Create Date: 2023-12-05 22:47:33.455372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fba311583c'
down_revision: Union[str, None] = '5b1fc71a077e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_options_question_id_fkey', 'answer_options', type_='foreignkey')
    op.create_foreign_key(None, 'answer_options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('levels_module_id_fkey', 'levels', type_='foreignkey')
    op.create_foreign_key(None, 'levels', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('modules_map_id_fkey', 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_task_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'task_units', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_units_level_id_fkey', 'task_units', type_='foreignkey')
    op.create_foreign_key(None, 'task_units', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_units', type_='foreignkey')
    op.create_foreign_key('task_units_level_id_fkey', 'task_units', 'levels', ['level_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_task_id_fkey', 'questions', 'task_units', ['task_id'], ['id'])
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key('modules_map_id_fkey', 'modules', 'maps', ['map_id'], ['id'])
    op.drop_constraint(None, 'levels', type_='foreignkey')
    op.create_foreign_key('levels_module_id_fkey', 'levels', 'modules', ['module_id'], ['id'])
    op.drop_constraint(None, 'answer_options', type_='foreignkey')
    op.create_foreign_key('answer_options_question_id_fkey', 'answer_options', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
