"""Добавляет связь между картой и модулями 

Revision ID: 9f5fe0dc8217
Revises: 24f2b6f0f8fd
Create Date: 2023-11-15 15:30:50.105149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5fe0dc8217'
down_revision: Union[str, None] = '24f2b6f0f8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('maps', 'name')
    op.add_column('modules', sa.Column('map_id', sa.UUID(), nullable=False))
    op.add_column('modules', sa.Column('title', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'modules', 'maps', ['map_id'], ['id'])
    op.drop_column('modules', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'title')
    op.drop_column('modules', 'map_id')
    op.add_column('maps', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('maps', 'title')
    # ### end Alembic commands ###
