"""удаляет поля почты, добавляет поле юзернейма

Revision ID: 1acf032a74df
Revises: c22a2503060b
Create Date: 2023-11-15 19:46:04.819280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acf032a74df'
down_revision: Union[str, None] = 'c22a2503060b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_email_key', 'employees', type_='unique')
    op.drop_column('employees', 'email')
    op.drop_constraint('tutors_email_key', 'tutors', type_='unique')
    op.drop_column('tutors', 'email')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'username')
    op.add_column('tutors', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('tutors_email_key', 'tutors', ['email'])
    op.add_column('employees', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('employees_email_key', 'employees', ['email'])
    # ### end Alembic commands ###
