"""добавляет каскадное удаление блоков теории

Revision ID: 2f3cf6083f65
Revises: c4fba311583c
Create Date: 2023-12-05 22:50:06.893743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3cf6083f65'
down_revision: Union[str, None] = 'c4fba311583c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('theory_units_level_id_fkey', 'theory_units', type_='foreignkey')
    op.create_foreign_key(None, 'theory_units', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theory_units', type_='foreignkey')
    op.create_foreign_key('theory_units_level_id_fkey', 'theory_units', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###
