"""добавляет связь между задачей и ответами

Revision ID: 43a526a12009
Revises: 5bbffa09568b
Create Date: 2023-11-19 10:35:20.123826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a526a12009'
down_revision: Union[str, None] = '5bbffa09568b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'questions', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('level_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'level_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'task_id')
    # ### end Alembic commands ###
