"""Добавляет внешние ключи

Revision ID: 5aa9681ef1db
Revises: 6e79091c3fb1
Create Date: 2023-11-02 17:33:20.640710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa9681ef1db'
down_revision: Union[str, None] = '6e79091c3fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('tutor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'employees', 'tutors', ['tutor_id'], ['id'])
    op.add_column('levels', sa.Column('module_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'levels', 'modules', ['module_id'], ['id'])
    op.add_column('modules', sa.Column('previous_module_id', sa.UUID(), nullable=False))
    op.add_column('modules', sa.Column('next_module_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'modules', 'modules', ['next_module_id'], ['id'])
    op.create_foreign_key(None, 'modules', 'modules', ['previous_module_id'], ['id'])
    op.add_column('theory_videos', sa.Column('theory_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'theory_videos', 'theory_blocks', ['theory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theory_videos', type_='foreignkey')
    op.drop_column('theory_videos', 'theory_id')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'next_module_id')
    op.drop_column('modules', 'previous_module_id')
    op.drop_constraint(None, 'levels', type_='foreignkey')
    op.drop_column('levels', 'module_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'tutor_id')
    # ### end Alembic commands ###
