"""возвращает employees_task

Revision ID: 363f3ee32613
Revises: 5bc679ad47df
Create Date: 2023-11-20 19:18:59.137319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '363f3ee32613'
down_revision: Union[str, None] = '5bc679ad47df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NotViewed', 'Viewed', 'Submitted', 'Finished', name='task_states').create(op.get_bind())
    op.create_table('task_employees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.ENUM('NotViewed', 'Viewed', 'Submitted', 'Finished', name='task_states', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_units.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_employees')
    sa.Enum('NotViewed', 'Viewed', 'Submitted', 'Finished', name='task_states').drop(op.get_bind())
    # ### end Alembic commands ###
