"""меняет в модели теории theme на title

Revision ID: 5bbffa09568b
Revises: da06417476fd
Create Date: 2023-11-19 00:49:49.197801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbffa09568b'
down_revision: Union[str, None] = 'da06417476fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theory_blocks', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('theory_blocks', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theory_blocks', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('theory_blocks', 'title')
    # ### end Alembic commands ###
