"""добавляет отчество сотрдуникам и куратору

Revision ID: ee38e6a7803e
Revises: 753c2ee49c0d
Create Date: 2023-12-16 18:32:42.403504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee38e6a7803e'
down_revision: Union[str, None] = '753c2ee49c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('patronymic', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutors', 'patronymic')
    # ### end Alembic commands ###
