"""временно удаляет таблицу с видео теории

Revision ID: e8496d8a36fc
Revises: e21d5fb84a66
Create Date: 2023-11-19 10:48:35.457329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8496d8a36fc'
down_revision: Union[str, None] = 'e21d5fb84a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theory_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theory_videos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['theory_id'], ['theory_blocks.id'], name='theory_videos_theory_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='theory_videos_pkey')
    )
    # ### end Alembic commands ###
