"""изменяет названия таблиц юнитов

Revision ID: 5bc679ad47df
Revises: 44d9eb94c16b
Create Date: 2023-11-20 19:17:54.479920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bc679ad47df'
down_revision: Union[str, None] = '44d9eb94c16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('Test', name='task_types', create_type=False), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('score_reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theory_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answers')
    op.drop_table('theory_blocks')
    op.create_foreign_key(None, 'questions', 'task_units', ['task_id'], ['id'])
    sa.Enum('NotViewed', 'Viewed', 'Submitted', 'Finished', name='task_states').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NotViewed', 'Viewed', 'Submitted', 'Finished', name='task_states').create(op.get_bind())
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_table('theory_blocks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='theory_blocks_level_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='theory_blocks_pkey')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    op.drop_table('answer_options')
    op.drop_table('theory_units')
    op.drop_table('task_units')
    # ### end Alembic commands ###
