"""Добавляет таблицы для создания уровней

Revision ID: 24f2b6f0f8fd
Revises: 5bc05f78249a
Create Date: 2023-11-15 15:21:40.114690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2b6f0f8fd'
down_revision: Union[str, None] = '5bc05f78249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_employees',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum(name='level_states'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'employee_id')
    )
    op.create_table('level_tasks',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'task_id')
    )
    op.create_table('level_theory_blocks',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('theory_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['theory_id'], ['theory_blocks.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'theory_id')
    )
    op.drop_column('levels', 'is_accomplished')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('is_accomplished', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('level_theory_blocks')
    op.drop_table('level_tasks')
    op.drop_table('level_employees')
    # ### end Alembic commands ###
