"""возвращает роли пользователя

Revision ID: 9a94a7ad2790
Revises: 1e7465593407
Create Date: 2023-11-16 15:02:38.538132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a94a7ad2790'
down_revision: Union[str, None] = '1e7465593407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Employee', 'Tutor', 'HR', name='user_roles').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('Employee', 'Tutor', 'HR', name='user_roles', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum('Employee', 'Tutor', 'HR', name='user_roles').drop(op.get_bind())
    # ### end Alembic commands ###
