"""добавляет связь между вопросами и ответами

Revision ID: e21d5fb84a66
Revises: 43a526a12009
Create Date: 2023-11-19 10:37:12.398132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21d5fb84a66'
down_revision: Union[str, None] = '43a526a12009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    # ### end Alembic commands ###
