"""меняет название колонки у ответа

Revision ID: 842b8bf56cef
Revises: e545a099be25
Create Date: 2023-11-19 22:30:13.120331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842b8bf56cef'
down_revision: Union[str, None] = 'e545a099be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer', sa.String(), nullable=False))
    op.drop_column('answers', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'answer')
    # ### end Alembic commands ###
