"""удаляет промежуточные таблицы

Revision ID: f074fb69a98a
Revises: 842b8bf56cef
Create Date: 2023-11-20 01:14:38.556334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f074fb69a98a'
down_revision: Union[str, None] = '842b8bf56cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level_tasks')
    op.drop_table('level_theory_blocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_theory_blocks',
    sa.Column('level_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('theory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='level_theory_blocks_level_id_fkey'),
    sa.ForeignKeyConstraint(['theory_id'], ['theory_blocks.id'], name='level_theory_blocks_theory_id_fkey'),
    sa.PrimaryKeyConstraint('level_id', 'theory_id', name='level_theory_blocks_pkey')
    )
    op.create_table('level_tasks',
    sa.Column('level_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='level_tasks_level_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='level_tasks_task_id_fkey'),
    sa.PrimaryKeyConstraint('level_id', 'task_id', name='level_tasks_pkey')
    )
    # ### end Alembic commands ###
