"""Изменяет определение перечислений, временно удаляет роль пользователя

Revision ID: 1e7465593407
Revises: 1acf032a74df
Create Date: 2023-11-16 15:01:09.555491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e7465593407'
down_revision: Union[str, None] = '1acf032a74df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum('employee', 'tutor', 'hr', name='user_roles').drop(op.get_bind())
    op.sync_enum_values('public', 'level_states', ['NotViewed', 'Viewed', 'Completed'],
                        [('level_employees', 'state')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'task_types', ['Test'],
                        [('tasks', 'type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'task_states', ['NotViewed', 'Viewed', 'Submitted', 'Finished'],
                        [('task_employees', 'state')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'question_types', ['SingleChoice', 'MultipleChoice'],
                        [('questions', 'type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'question_types', [],
                        [('questions', 'type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'task_states', [],
                        [('task_employees', 'state')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'task_types', [],
                        [('tasks', 'type')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'level_states', [],
                        [('level_employees', 'state')],
                        enum_values_to_rename=[])
    sa.Enum('employee', 'tutor', 'hr', name='user_roles').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('employee', 'tutor', 'hr', name='user_roles', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
