"""переносит ответственность за правильный вариант ответа на вопроса на ответ

Revision ID: a2f543f8e4c6
Revises: f074fb69a98a
Create Date: 2023-11-20 12:48:48.808979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f543f8e4c6'
down_revision: Union[str, None] = 'f074fb69a98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_answer_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
