"""empty message

Revision ID: 29ed19cdffbf
Revises: b71a5f16b60e
Create Date: 2023-11-18 17:23:49.682134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ed19cdffbf'
down_revision: Union[str, None] = 'b71a5f16b60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'previous_module_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('modules', 'next_module_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modules', 'next_module_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('modules', 'previous_module_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
